apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
        - name: doctor-service
          image: gcr.io/cloud-445107/doctor-service:latest
          ports:
            - containerPort: 8002
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: healthsync-secrets
                  key: mongo-url
            - name: REDSHIFT_HOST
              valueFrom:
                secretKeyRef:
                  name: healthsync-secrets
                  key: redshift-host
            - name: REDSHIFT_USER
              valueFrom:
                secretKeyRef:
                  name: healthsync-secrets
                  key: redshift-user
            - name: REDSHIFT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: healthsync-secrets
                  key: redshift-password