apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: gcr.io/healthsync-445122/analytics-service:latest
          ports:
            - containerPort: 8004
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: healthsync-secrets
                  key: mongo-url
            - name: REDSHIFT_HOST
              valueFrom:
                secretKeyRef:
                  name: healthsync-secrets
                  key: redshift-host
            - name: REDSHIFT_USER
              valueFrom:
                secretKeyRef:
                  name: healthsync-secrets
                  key: redshift-user
            - name: REDSHIFT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: healthsync-secrets
                  key: redshift-password